In [89]:
import pandas as pd
import numpy as np

### GDP CLEANER

In [90]:
gdppc = pd.read_csv("matched_gdp.csv")
gdppc.replace("N/A", np.nan, inplace=True)
gdppc = gdppc.drop(columns=["Indicator Name", "Indicator Code"])
gdppc_long = gdppc.melt(id_vars=["Country Code"], var_name="Year", value_name="gdp_per_capita")
gdppc_long['Year'] = gdppc_long['Year'].astype(str)
gdppc_long_cleaned = gdppc_long[~gdppc_long['Year'].str.contains("Unnamed", na=False)]
gdppc_long_cleaned['Year'] = pd.to_numeric(gdppc_long_cleaned['Year'], errors='coerce', downcast='integer')
gdppc_long_cleaned = gdppc_long_cleaned.dropna(subset=['Year'])
gdppc_long_cleaned['Year'] = gdppc_long_cleaned['Year'].astype(int)
gdppc_long_cleaned = gdppc_long_cleaned.dropna(subset=['Country Code'])
gdppc_long_cleaned.to_csv("wb_gdp_per_capita.csv", index=False)
gdppc_long_cleaned

      Country Code  Year  gdp_per_capita
0              AFG  1960             NaN
1              AGO  1960             NaN
2              ALB  1960             NaN
3              ARE  1960             NaN
4              ARG  1960     7397.109655
...            ...   ...             ...
13115          WSM  2023     4003.075902
13116          YEM  2023      859.209303
13117          ZAF  2023     5747.419650
13118          ZMB  2023     1330.859982
13119          ZWE  2023     1410.737311

[13120 rows x 3 columns]

### LIFE EXPECTANCY CLEANER

In [91]:
lifeexpectancy = pd.read_csv('matched_life_exp.csv')
lifeexpectancy.replace("N/A", np.nan, inplace=True)
lifeexpectancy = lifeexpectancy.drop(columns=["Indicator Name", "Indicator Code"])
lifeexpectancy_long = lifeexpectancy.melt(id_vars=["Country Code"], var_name="Year", value_name="life_expectancy")
lifeexpectancy_long['Year'] = lifeexpectancy_long['Year'].astype(str)
lifeexpectancy_long = lifeexpectancy_long[~lifeexpectancy_long['Year'].str.contains("Unnamed", na=False)]
lifeexpectancy_long['Year'] = pd.to_numeric(lifeexpectancy_long['Year'], errors='coerce', downcast='integer')
lifeexpectancy_long = lifeexpectancy_long.dropna(subset=['Year'])
lifeexpectancy_long['Year'] = lifeexpectancy_long['Year'].astype(int)
lifeexpectancy_long = lifeexpectancy_long[~((lifeexpectancy_long['Country Code'] == 'N/A') & (lifeexpectancy_long['life_expectancy'] == 'N/A'))]
lifeexpectancy_long.to_csv("wb_life_expectancy.csv", index=False)
lifeexpectancy_long

      Country Code  Year  life_expectancy
0              AFG  1960           32.535
1              AGO  1960           38.211
2              ALB  1960           54.439
3              ARE  1960           48.811
4              ARG  1960           63.978
...            ...   ...              ...
13115          WSM  2023              NaN
13116          YEM  2023              NaN
13117          ZAF  2023              NaN
13118          ZMB  2023              NaN
13119          ZWE  2023              NaN

[13120 rows x 3 columns]

### LITERACY RATE CLEANER

In [92]:
literacyrates = pd.read_csv('matched_lit_rate.csv')
literacyrates.replace("N/A", np.nan, inplace=True)
literacyrates_long = literacyrates.melt(id_vars=["Country Code"], var_name="Year", value_name="literacy_rate")
literacyrates_long['Year'] = literacyrates_long['Year'].astype(str)
literacyrates_long = literacyrates_long[~literacyrates_long['Year'].str.contains("Unnamed", na=False)]
literacyrates_long['Year'] = pd.to_numeric(literacyrates_long['Year'], errors='coerce', downcast='integer')
literacyrates_long = literacyrates_long.dropna(subset=['Year'])
literacyrates_long['Year'] = literacyrates_long['Year'].astype(int)
literacyrates_long = literacyrates_long[~((literacyrates_long['Country Code'] == 'N/A') & (literacyrates_long['literacy_rate'] == 'N/A'))]
literacyrates_long.to_csv("wb_literacy_rates.csv", index=False)
literacyrates_long

      Country Code  Year literacy_rate
410            AFG  1960           NaN
411            AGO  1960           NaN
412            ALB  1960           NaN
413            ARE  1960           NaN
414            ARG  1960           NaN
...            ...   ...           ...
13525          WSM  2023           NaN
13526          YEM  2023           NaN
13527          ZAF  2023           NaN
13528          ZMB  2023           NaN
13529          ZWE  2023           NaN

[13120 rows x 3 columns]

### URBAN POPULATION CLEANER

In [93]:
urbanpop = pd.read_csv('matched_urban_pop.csv')
urbanpop.replace("N/A", np.nan, inplace=True)
urbanpop = urbanpop.drop(columns=["Indicator Name", "Indicator Code"])
urbanpop_long = urbanpop.melt(id_vars=["Country Code"], var_name="Year", value_name="urban_pop_percentage")
urbanpop_long['Year'] = urbanpop_long['Year'].astype(str)
urbanpop_long = urbanpop_long[~urbanpop_long['Year'].str.contains("Unnamed", na=False)]
urbanpop_long['Year'] = pd.to_numeric(urbanpop_long['Year'], errors='coerce', downcast='integer')
urbanpop_long = urbanpop_long.dropna(subset=['Year'])
urbanpop_long['Year'] = urbanpop_long['Year'].astype(int)
urbanpop_long = urbanpop_long[~((urbanpop_long['Country Code'] == 'N/A') & (urbanpop_long['urban_pop_percentage'] == 'N/A'))]
urbanpop_long.to_csv("wb_urban_pop_percentage.csv", index=False)
urbanpop_long

      Country Code  Year  urban_pop_percentage
0              AFG  1960                 8.401
1              AGO  1960                10.435
2              ALB  1960                30.705
3              ARE  1960                73.500
4              ARG  1960                73.611
...            ...   ...                   ...
13115          WSM  2023                17.508
13116          YEM  2023                39.831
13117          ZAF  2023                68.819
13118          ZMB  2023                46.335
13119          ZWE  2023                32.517

[13120 rows x 3 columns]

### TOURISM CLEANER

In [94]:
tourism = pd.read_csv('matched_tourism.csv')
tourism.replace("N/A", np.nan, inplace=True)
tourism = tourism.drop(columns=["Indicator Name", "Indicator Code"])
tourism_long = tourism.melt(id_vars=["Country Code"], var_name="Year", value_name="tourism")
tourism_long['Year'] = tourism_long['Year'].astype(str)
tourism_long = tourism_long[~tourism_long['Year'].str.contains("Unnamed", na=False)]
tourism_long['Year'] = pd.to_numeric(tourism_long['Year'], errors='coerce', downcast='integer')
tourism_long = tourism_long.dropna(subset=['Year'])
tourism_long['Year'] = tourism_long['Year'].astype(int)
tourism_long = tourism_long[~((tourism_long['Country Code'] == 'N/A') & (tourism_long['tourism'] == 'N/A'))]
tourism_long.to_csv("wb_tourism.csv", index=False)
tourism_long

      Country Code  Year  tourism
0              AFG  1960      NaN
1              AGO  1960      NaN
2              ALB  1960      NaN
3              ARE  1960      NaN
4              ARG  1960      NaN
...            ...   ...      ...
13115          WSM  2023      NaN
13116          YEM  2023      NaN
13117          ZAF  2023      NaN
13118          ZMB  2023      NaN
13119          ZWE  2023      NaN

[13120 rows x 3 columns]